services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 109110
      POSTGRES_DB: email_organizer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_TYPE: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 109110
      DATABASE_NAME: email_organizer
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    environment:
      NODE_ENV: production
      # Add any other frontend env vars here if needed
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: {}
